# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Gilded Rose services

    gilded_rose.product_factory:
      class: GildedRose\ProductFactory
    GildedRose\ProductFactory: '@gilded_rose.product_factory'

    gilded_rose.gilded_rose:
      class: GildedRose\GildedRose
      arguments: ["@=service('app.gilded_rose_storage').getItems()"]
    GildedRose\GildedRose: '@gilded_rose.gilded_rose'

    gilded_rose.product_factory_registry:
      class: GildedRose\ProductFactoryRegistry
      calls:
        - method: register
          arguments:
            - 'GildedRose\Products\RegularProduct'
        - method: register
          arguments:
            - 'GildedRose\Products\AgedBrie'
        - method: register
          arguments:
            - 'GildedRose\Products\Sulfuras'
        - method: register
          arguments:
            - 'GildedRose\Products\BackstagePass'
        - method: register
          arguments:
            - 'GildedRose\Products\Conjured'

    GildedRose\ProductFactoryRegistry: '@gilded_rose.product_factory_registry'

    app.gilded_rose_storage:
      class: App\GildedRose\GildedRoseStorage
    App\GildedRose\GildedRoseStorage: '@app.gilded_rose_storage'

    app.gilded_rose_store:
      class: App\GildedRose\GildedRoseStore
      calls:
        - method: executeNewDay
    App\GildedRose\GildedRoseStore: '@app.gilded_rose_store'

    # End of Gilded Rose services